use std::collections::{BTreeMap, HashMap, HashSet};

use serde::Serialize;
use xxhash_rust::xxh3::xxh3_64;

use crate::{
    analysis::{
        callgraph::{FunctionNode, NodeIndex},
        fingerprint::{LayoutShiftBody, layout_shift_body, normalized_body},
        matching::MatchTarget,
    },
    obj::ObjSectionKind,
    util::split::default_section_align,
};

pub const COVERAGE_SCHEMA: u32 = 2;
pub const POLICY_VERSION: u32 = 2;
pub const MIN_ANCHOR_BYTES: u32 = 128;
pub const MIN_LAYOUT_SHIFT_FUNCTIONS: u32 = 2;
pub const MIN_LAYOUT_SHIFT_CHANGED_ACCESSES: u32 = 4;
pub const MIN_LAYOUT_SHIFT_BYTES: u32 = 128;

#[derive(Debug, Serialize)]
pub struct CoverageReport {
    pub schema: u32,
    pub policy: CoveragePolicy,
    pub source: String,
    pub target: String,
    pub target_ownership_masked: bool,
    pub source_units: Vec<CoverageUnit>,
    pub target_layout: Vec<TargetFunction>,
}

#[derive(Debug, Serialize)]
pub struct CoveragePolicy {
    pub version: u32,
    pub minimum_anchor_bytes: u32,
    pub normalized_body_must_be_unique: bool,
    pub confirm_normalized_bytes_after_hash: bool,
    pub require_relocation_layout: bool,
    pub require_known_extents: bool,
    pub require_explicit_whole_source_ownership: bool,
    pub reject_weak_symbols: bool,
    pub reject_template_anchors: bool,
    pub reject_conflicting_target_ownership: bool,
    pub require_split_alignment: bool,
    pub infer_this_relative_layout_shifts: bool,
    pub minimum_layout_shift_functions: u32,
    pub minimum_layout_shift_changed_accesses: u32,
    pub minimum_layout_shift_bytes: u32,
    pub maximum_layout_shift_segments: u32,
}

#[derive(Debug, Serialize)]
pub struct CoverageUnit {
    pub name: String,
    pub code_bytes: u64,
    pub autogenerated: bool,
    pub source_functions: u32,
    pub no_exact_target_body: u32,
    pub name_only_candidates: u32,
    pub ambiguous_exact_bodies: u32,
    pub anchors: Vec<CoverageAnchor>,
    pub layout_shift_candidates: u32,
    pub layout_shift_anchors: Vec<LayoutShiftAnchor>,
}

#[derive(Debug, Serialize)]
pub struct CoverageAnchor {
    pub source_name: String,
    pub source_address: String,
    pub target_name: String,
    pub target_address: String,
    pub target_end: String,
    pub section: String,
    pub size: u32,
    pub source_local: bool,
    pub target_local: bool,
    pub source_weak: bool,
    pub target_weak: bool,
    pub source_extent_known: bool,
    pub target_extent_known: bool,
    pub source_unit_explicit: bool,
    pub source_unit_wholly_owned: bool,
    pub template_instantiation: bool,
    pub unique_source: bool,
    pub unique_target: bool,
    pub normalized_body_equal: bool,
    pub relocation_layout_equal: bool,
    pub required_alignment: u32,
    pub existing_target_owner: Option<String>,
    pub existing_owner_autogenerated: bool,
    pub eligible: bool,
    pub reasons: Vec<&'static str>,
}

#[derive(Debug, Clone, Serialize)]
pub struct LayoutShiftAnchor {
    pub source_name: String,
    pub source_address: String,
    pub target_name: String,
    pub target_address: String,
    pub target_end: String,
    pub section: String,
    pub size: u32,
    pub source_local: bool,
    pub target_local: bool,
    pub source_weak: bool,
    pub target_weak: bool,
    pub source_extent_known: bool,
    pub target_extent_known: bool,
    pub source_unit_explicit: bool,
    pub source_unit_wholly_owned: bool,
    pub template_instantiation: bool,
    pub unique_source: bool,
    pub unique_target: bool,
    pub layout_masked_body_equal: bool,
    pub relocation_layout_equal: bool,
    pub this_accesses: u32,
    pub changed_this_accesses: u32,
    pub offset_delta: i32,
    pub inferred_breakpoint: Option<i32>,
    pub support_group: String,
    pub support_functions: u32,
    pub support_bytes: u32,
    pub support_changed_accesses: u32,
    pub required_alignment: u32,
    pub existing_target_owner: Option<String>,
    pub existing_owner_autogenerated: bool,
    pub eligible: bool,
    pub reasons: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct TargetFunction {
    pub address: String,
    pub end: String,
    pub section: String,
    pub current_owner: Option<String>,
    pub owner_autogenerated: bool,
}

pub fn build_report(
    source: &MatchTarget,
    target: &MatchTarget,
    mask_target_ownership: bool,
) -> CoverageReport {
    let mut source_hashes: HashMap<u64, Vec<NodeIndex>> = HashMap::new();
    let mut target_hashes: HashMap<u64, Vec<NodeIndex>> = HashMap::new();
    for node in 0..source.graph.len() as NodeIndex {
        source_hashes.entry(source.fingerprints[node as usize].exact_hash).or_default().push(node);
    }
    for node in 0..target.graph.len() as NodeIndex {
        target_hashes.entry(target.fingerprints[node as usize].exact_hash).or_default().push(node);
    }
    let target_names: HashSet<&str> =
        (0..target.graph.len() as NodeIndex).map(|node| target.symbol_name(node)).collect();

    let mut units: BTreeMap<String, CoverageUnit> = BTreeMap::new();
    for (_, section, start, split) in source.obj.sections.all_splits() {
        let entry = units.entry(split.unit.clone()).or_insert_with(|| CoverageUnit {
            name: split.unit.clone(),
            code_bytes: 0,
            autogenerated: source.obj.is_unit_autogenerated(&split.unit),
            source_functions: 0,
            no_exact_target_body: 0,
            name_only_candidates: 0,
            ambiguous_exact_bodies: 0,
            anchors: Vec::new(),
            layout_shift_candidates: 0,
            layout_shift_anchors: Vec::new(),
        });
        if section.kind == ObjSectionKind::Code {
            let end =
                if split.end == 0 { (section.address + section.size) as u32 } else { split.end };
            entry.code_bytes += end.saturating_sub(start) as u64;
        }
    }

    for source_node in 0..source.graph.len() as NodeIndex {
        let Some(unit) = source.unit_of(source_node) else { continue };
        let source_name = source.symbol_name(source_node);
        if let Some(entry) = units.get_mut(unit) {
            entry.source_functions += 1;
        }
        let fingerprint = &source.fingerprints[source_node as usize];
        let source_candidate = unique_hash_node(&source_hashes, fingerprint.exact_hash);
        if source_candidate != Some(source_node) {
            if let Some(entry) = units.get_mut(unit) {
                entry.ambiguous_exact_bodies += 1;
            }
            continue;
        }
        if !target_hashes.contains_key(&fingerprint.exact_hash) {
            if let Some(entry) = units.get_mut(unit) {
                entry.no_exact_target_body += 1;
                entry.name_only_candidates += u32::from(target_names.contains(source_name));
            }
            continue;
        }
        let target_candidate = unique_hash_node(&target_hashes, fingerprint.exact_hash);
        if target_candidate.is_none() {
            if let Some(entry) = units.get_mut(unit) {
                entry.ambiguous_exact_bodies += 1;
            }
            continue;
        }
        let target_node = target_candidate.unwrap();
        let a = source.graph.node(source_node);
        let b = target.graph.node(target_node);
        let target_name = target.symbol_name(target_node);
        let target_owner = (!mask_target_ownership)
            .then(|| target.unit_of(target_node).map(str::to_string))
            .flatten();
        let owner_auto =
            target_owner.as_deref().is_some_and(|name| target.obj.is_unit_autogenerated(name));
        let source_body = normalized_body(&source.obj, a);
        let target_body = normalized_body(&target.obj, b);
        let source_extent_known =
            source.obj.symbols[a.symbol].size_known && source_body.len() == a.size as usize;
        let target_extent_known =
            target.obj.symbols[b.symbol].size_known && target_body.len() == b.size as usize;
        let body_equal = source_body == target_body;
        let reloc_equal = relocation_layout(a) == relocation_layout(b);
        let template =
            is_template_symbol(source, source_node) || is_template_symbol(target, target_node);
        let source_unit_explicit = !source.obj.is_unit_autogenerated(unit);
        let source_unit_wholly_owned =
            range_is_owned_by(source, a.section, a.address, a.address + a.size, unit);
        let section = &target.obj.sections[b.section];
        let align = required_alignment(target, b);
        let mut reasons = eligibility_reasons(
            a.size,
            source.is_weak(source_node),
            target.is_weak(target_node),
            source_extent_known,
            target_extent_known,
            source_unit_explicit,
            source_unit_wholly_owned,
            template,
            body_equal,
            reloc_equal,
            target_owner.as_deref(),
            owner_auto,
            unit,
        );
        if b.address % align != 0 || (b.address + b.size) % align != 0 {
            reasons.push("function range is not split-aligned");
        }
        units
            .entry(unit.to_string())
            .or_insert_with(|| CoverageUnit {
                name: unit.to_string(),
                code_bytes: 0,
                autogenerated: source.obj.is_unit_autogenerated(unit),
                source_functions: 0,
                no_exact_target_body: 0,
                name_only_candidates: 0,
                ambiguous_exact_bodies: 0,
                anchors: Vec::new(),
                layout_shift_candidates: 0,
                layout_shift_anchors: Vec::new(),
            })
            .anchors
            .push(CoverageAnchor {
                source_name: source_name.to_string(),
                source_address: hex(a.address),
                target_name: if mask_target_ownership {
                    String::new()
                } else {
                    target_name.to_string()
                },
                target_address: hex(b.address),
                target_end: hex(b.address + b.size),
                section: section.name.clone(),
                size: a.size,
                source_local: source.is_local(source_node),
                target_local: target.is_local(target_node),
                source_weak: source.is_weak(source_node),
                target_weak: target.is_weak(target_node),
                source_extent_known,
                target_extent_known,
                source_unit_explicit,
                source_unit_wholly_owned,
                template_instantiation: template,
                unique_source: true,
                unique_target: true,
                normalized_body_equal: body_equal,
                relocation_layout_equal: reloc_equal,
                required_alignment: align,
                existing_target_owner: target_owner,
                existing_owner_autogenerated: owner_auto,
                eligible: reasons.is_empty(),
                reasons,
            });
    }

    add_layout_shift_evidence(source, target, mask_target_ownership, &mut units);

    for unit in units.values_mut() {
        unit.anchors
            .sort_by(|a, b| b.size.cmp(&a.size).then(a.target_address.cmp(&b.target_address)));
        unit.layout_shift_anchors.sort_by(|a, b| {
            a.support_group.cmp(&b.support_group).then(a.target_address.cmp(&b.target_address))
        });
    }
    let target_layout = target
        .layout()
        .iter()
        .map(|&index| {
            let node = target.graph.node(index);
            let owner = (!mask_target_ownership)
                .then(|| target.unit_of(index).map(str::to_string))
                .flatten();
            TargetFunction {
                address: hex(node.address),
                end: hex(node.address + node.size),
                section: target.obj.sections[node.section].name.clone(),
                owner_autogenerated: owner
                    .as_deref()
                    .is_some_and(|name| target.obj.is_unit_autogenerated(name)),
                current_owner: owner,
            }
        })
        .collect();

    CoverageReport {
        schema: COVERAGE_SCHEMA,
        policy: CoveragePolicy {
            version: POLICY_VERSION,
            minimum_anchor_bytes: MIN_ANCHOR_BYTES,
            normalized_body_must_be_unique: true,
            confirm_normalized_bytes_after_hash: true,
            require_relocation_layout: true,
            require_known_extents: true,
            require_explicit_whole_source_ownership: true,
            reject_weak_symbols: true,
            reject_template_anchors: true,
            reject_conflicting_target_ownership: true,
            require_split_alignment: true,
            infer_this_relative_layout_shifts: true,
            minimum_layout_shift_functions: MIN_LAYOUT_SHIFT_FUNCTIONS,
            minimum_layout_shift_changed_accesses: MIN_LAYOUT_SHIFT_CHANGED_ACCESSES,
            minimum_layout_shift_bytes: MIN_LAYOUT_SHIFT_BYTES,
            maximum_layout_shift_segments: 2,
        },
        source: source.name.clone(),
        target: target.name.clone(),
        target_ownership_masked: mask_target_ownership,
        source_units: units.into_values().collect(),
        target_layout,
    }
}

#[derive(Debug, Clone)]
struct OffsetTransform {
    delta: i32,
    breakpoint: Option<i32>,
    changed_accesses: u32,
}

#[derive(Debug, Clone)]
struct LayoutPair {
    unit: String,
    source: NodeIndex,
    target: NodeIndex,
    observations: Vec<(i32, i32)>,
    transform: OffsetTransform,
    base_reasons: Vec<String>,
}

fn add_layout_shift_evidence(
    source: &MatchTarget,
    target: &MatchTarget,
    mask_target_ownership: bool,
    units: &mut BTreeMap<String, CoverageUnit>,
) {
    let source_bodies: Vec<LayoutShiftBody> = (0..source.graph.len() as NodeIndex)
        .map(|node| layout_shift_body(&source.obj, source.graph.node(node)))
        .collect();
    let target_bodies: Vec<LayoutShiftBody> = (0..target.graph.len() as NodeIndex)
        .map(|node| layout_shift_body(&target.obj, target.graph.node(node)))
        .collect();
    let source_hashes = layout_hashes(&source_bodies);
    let target_hashes = layout_hashes(&target_bodies);
    let mut pairs = Vec::new();

    for source_node in 0..source.graph.len() as NodeIndex {
        let Some(unit) = source.unit_of(source_node) else { continue };
        let a = source.graph.node(source_node);
        let source_body = &source_bodies[source_node as usize];
        if a.size < 16
            || source_body.accesses.is_empty()
            || unique_hash_node(&source_hashes, source_body.hash) != Some(source_node)
        {
            continue;
        }
        let Some(target_node) = unique_hash_node(&target_hashes, source_body.hash) else {
            continue;
        };
        let b = target.graph.node(target_node);
        let target_body = &target_bodies[target_node as usize];
        if source_body.bytes != target_body.bytes
            || source.fingerprints[source_node as usize].exact_hash
                == target.fingerprints[target_node as usize].exact_hash
        {
            continue;
        }
        let Some(observations) = corresponding_accesses(source_body, target_body) else { continue };
        let Some(transform) = infer_offset_transform(&observations) else { continue };

        let source_extent_known = source.obj.symbols[a.symbol].size_known
            && normalized_body(&source.obj, a).len() == a.size as usize;
        let target_extent_known = target.obj.symbols[b.symbol].size_known
            && normalized_body(&target.obj, b).len() == b.size as usize;
        let target_owner = (!mask_target_ownership)
            .then(|| target.unit_of(target_node).map(str::to_string))
            .flatten();
        let owner_auto =
            target_owner.as_deref().is_some_and(|name| target.obj.is_unit_autogenerated(name));
        let source_unit_explicit = !source.obj.is_unit_autogenerated(unit);
        let source_unit_wholly_owned =
            range_is_owned_by(source, a.section, a.address, a.address + a.size, unit);
        let template =
            is_template_symbol(source, source_node) || is_template_symbol(target, target_node);
        let reloc_equal = relocation_layout(a) == relocation_layout(b);
        let align = required_alignment(target, b);
        let mut reasons = Vec::new();
        if source.is_weak(source_node) || target.is_weak(target_node) {
            reasons.push("weak symbol cannot establish ownership".to_string());
        }
        if !source_extent_known || !target_extent_known {
            reasons.push("function extent is not completely known".to_string());
        }
        if !source_unit_explicit {
            reasons.push("source unit is autogenerated".to_string());
        }
        if !source_unit_wholly_owned {
            reasons.push("source function is not wholly owned by one unit".to_string());
        }
        if template {
            reasons.push("template instantiation cannot establish ownership alone".to_string());
        }
        if !reloc_equal {
            reasons.push("relocation layout differs".to_string());
        }
        if target_owner.as_deref().is_some_and(|name| name != unit && !owner_auto) {
            reasons.push("target range is owned by another explicit unit".to_string());
        }
        if b.address % align != 0 || (b.address + b.size) % align != 0 {
            reasons.push("function range is not split-aligned".to_string());
        }
        pairs.push(LayoutPair {
            unit: unit.to_string(),
            source: source_node,
            target: target_node,
            observations,
            transform,
            base_reasons: reasons,
        });
    }

    let mut groups: BTreeMap<(String, crate::obj::SectionIndex, i32), Vec<usize>> = BTreeMap::new();
    for (index, pair) in pairs.iter().enumerate() {
        let section = target.graph.node(pair.target).section;
        groups.entry((pair.unit.clone(), section, pair.transform.delta)).or_default().push(index);
    }

    for ((unit_name, _, delta), indexes) in groups {
        let support: Vec<usize> =
            indexes.iter().copied().filter(|&index| pairs[index].base_reasons.is_empty()).collect();
        let observations: Vec<(i32, i32)> =
            support.iter().flat_map(|&index| pairs[index].observations.iter().copied()).collect();
        let group_transform = infer_offset_transform(&observations);
        let support_functions = support.len() as u32;
        let support_bytes: u32 = support
            .iter()
            .map(|&index| source.graph.node(pairs[index].source).size)
            .fold(0, u32::saturating_add);
        let support_changed_accesses =
            group_transform.as_ref().map_or(0, |transform| transform.changed_accesses);
        let mut group_reasons = Vec::new();
        if support_functions < MIN_LAYOUT_SHIFT_FUNCTIONS {
            group_reasons.push("layout shift lacks a second corroborating function".to_string());
        }
        if support_bytes < MIN_LAYOUT_SHIFT_BYTES {
            group_reasons.push("layout-shift support is smaller than policy minimum".to_string());
        }
        if support_changed_accesses < MIN_LAYOUT_SHIFT_CHANGED_ACCESSES {
            group_reasons
                .push("layout shift has too few changed this-relative accesses".to_string());
        }
        if group_transform.is_none() {
            group_reasons
                .push("functions disagree on one simple layout transformation".to_string());
        }
        let group_id = layout_group_id(source, target, delta, &support);

        if let Some(unit) = units.get_mut(&unit_name) {
            unit.layout_shift_candidates += indexes.len() as u32;
        }
        for index in indexes {
            let pair = &pairs[index];
            let a = source.graph.node(pair.source);
            let b = target.graph.node(pair.target);
            let source_body = &source_bodies[pair.source as usize];
            let target_body = &target_bodies[pair.target as usize];
            let source_name = source.symbol_name(pair.source);
            let target_name = target.symbol_name(pair.target);
            let target_owner = (!mask_target_ownership)
                .then(|| target.unit_of(pair.target).map(str::to_string))
                .flatten();
            let owner_auto =
                target_owner.as_deref().is_some_and(|name| target.obj.is_unit_autogenerated(name));
            let section = &target.obj.sections[b.section];
            let align = required_alignment(target, b);
            let mut reasons = pair.base_reasons.clone();
            reasons.extend(group_reasons.iter().cloned());
            if !support.contains(&index) && group_reasons.is_empty() {
                reasons
                    .push("function failed an individual layout-shift ownership gate".to_string());
            }
            let transform = group_transform.as_ref().unwrap_or(&pair.transform);
            units
                .get_mut(&unit_name)
                .expect("source unit was collected before function evidence")
                .layout_shift_anchors
                .push(LayoutShiftAnchor {
                    source_name: source_name.to_string(),
                    source_address: hex(a.address),
                    target_name: if mask_target_ownership {
                        String::new()
                    } else {
                        target_name.to_string()
                    },
                    target_address: hex(b.address),
                    target_end: hex(b.address + b.size),
                    section: section.name.clone(),
                    size: a.size,
                    source_local: source.is_local(pair.source),
                    target_local: target.is_local(pair.target),
                    source_weak: source.is_weak(pair.source),
                    target_weak: target.is_weak(pair.target),
                    source_extent_known: source.obj.symbols[a.symbol].size_known
                        && normalized_body(&source.obj, a).len() == a.size as usize,
                    target_extent_known: target.obj.symbols[b.symbol].size_known
                        && normalized_body(&target.obj, b).len() == b.size as usize,
                    source_unit_explicit: !source.obj.is_unit_autogenerated(&unit_name),
                    source_unit_wholly_owned: range_is_owned_by(
                        source,
                        a.section,
                        a.address,
                        a.address + a.size,
                        &unit_name,
                    ),
                    template_instantiation: is_template_symbol(source, pair.source)
                        || is_template_symbol(target, pair.target),
                    unique_source: true,
                    unique_target: true,
                    layout_masked_body_equal: source_body.bytes == target_body.bytes,
                    relocation_layout_equal: relocation_layout(a) == relocation_layout(b),
                    this_accesses: pair.observations.len() as u32,
                    changed_this_accesses: pair.transform.changed_accesses,
                    offset_delta: transform.delta,
                    inferred_breakpoint: transform.breakpoint,
                    support_group: group_id.clone(),
                    support_functions,
                    support_bytes,
                    support_changed_accesses,
                    required_alignment: align,
                    existing_target_owner: target_owner,
                    existing_owner_autogenerated: owner_auto,
                    eligible: reasons.is_empty(),
                    reasons,
                });
        }
    }
}

fn layout_hashes(bodies: &[LayoutShiftBody]) -> HashMap<u64, Vec<NodeIndex>> {
    let mut hashes = HashMap::new();
    for (index, body) in bodies.iter().enumerate() {
        if !body.accesses.is_empty() {
            hashes.entry(body.hash).or_insert_with(Vec::new).push(index as NodeIndex);
        }
    }
    hashes
}

fn corresponding_accesses(
    source: &LayoutShiftBody,
    target: &LayoutShiftBody,
) -> Option<Vec<(i32, i32)>> {
    if source.accesses.len() != target.accesses.len() || source.accesses.is_empty() {
        return None;
    }
    source
        .accesses
        .iter()
        .zip(&target.accesses)
        .map(|(a, b)| {
            (a.instruction_offset == b.instruction_offset
                && plausible_object_offset(a.object_offset)
                && plausible_object_offset(b.object_offset))
            .then_some((a.object_offset, b.object_offset))
        })
        .collect()
}

fn plausible_object_offset(offset: i32) -> bool { (0..=0x10000).contains(&offset) }

fn infer_offset_transform(observations: &[(i32, i32)]) -> Option<OffsetTransform> {
    let mut mappings = BTreeMap::new();
    for &(source, target) in observations {
        if mappings.insert(source, target).is_some_and(|previous| previous != target) {
            return None;
        }
    }
    let nonzero: HashSet<i32> = mappings
        .iter()
        .map(|(&source, &target)| target.wrapping_sub(source))
        .filter(|&delta| delta != 0)
        .collect();
    if nonzero.len() != 1 {
        return None;
    }
    let delta = *nonzero.iter().next().unwrap();
    let mut previous_delta = None;
    let mut transitions = 0;
    let mut previous_target = None;
    let mut breakpoint = None;
    for (&source, &target) in &mappings {
        let current_delta = target.wrapping_sub(source);
        if current_delta != 0 && current_delta != delta {
            return None;
        }
        if previous_target.is_some_and(|previous| target <= previous) {
            return None;
        }
        if previous_delta.is_some_and(|previous| previous != current_delta) {
            transitions += 1;
            breakpoint.get_or_insert(source);
        }
        if transitions > 1 {
            return None;
        }
        previous_delta = Some(current_delta);
        previous_target = Some(target);
    }
    let changed_accesses =
        observations.iter().filter(|(source, target)| source != target).count() as u32;
    Some(OffsetTransform { delta, breakpoint, changed_accesses })
}

fn layout_group_id(
    source: &MatchTarget,
    target: &MatchTarget,
    delta: i32,
    support: &[usize],
) -> String {
    let mut identity = delta.to_be_bytes().to_vec();
    for &index in support {
        // `support` contains indexes into the caller's pair vector, so only its
        // stable ordinal is needed to distinguish independently supported groups.
        identity.extend_from_slice(&(index as u64).to_be_bytes());
    }
    format!("layout-shift:{}:{}:{:016x}", source.name, target.name, xxh3_64(&identity))
}

fn required_alignment(target: &MatchTarget, node: &FunctionNode) -> u32 {
    let section = &target.obj.sections[node.section];
    target
        .obj
        .symbols
        .for_section_range(node.section, node.address..node.address + node.size)
        .filter(|&(_, symbol)| symbol.size_known && symbol.size > 0)
        .filter_map(|(_, symbol)| symbol.align)
        .max()
        .unwrap_or(default_section_align(section) as u32)
        .max(default_section_align(section) as u32)
}

fn relocation_layout(node: &FunctionNode) -> Vec<(u32, crate::obj::ObjRelocKind)> {
    node.refs.iter().map(|reference| (reference.offset, reference.kind)).collect()
}

fn is_template_name(name: &str) -> bool {
    let callable = name.split_once('(').map_or(name, |(callable, _)| callable);
    callable.contains('<') && callable.contains('>')
}

fn is_template_symbol(target: &MatchTarget, node: NodeIndex) -> bool {
    let symbol = &target.obj.symbols[target.graph.node(node).symbol];
    is_template_name(symbol.demangled_name.as_deref().unwrap_or(&symbol.name))
}

fn unique_hash_node(hashes: &HashMap<u64, Vec<NodeIndex>>, hash: u64) -> Option<NodeIndex> {
    let nodes = hashes.get(&hash)?;
    (nodes.len() == 1).then_some(nodes[0])
}

/// Confirm that the complete function interval belongs to one explicit source
/// split, rather than inferring ownership from its first instruction alone.
fn range_is_owned_by(
    object: &MatchTarget,
    section_index: crate::obj::SectionIndex,
    start: u32,
    end: u32,
    unit: &str,
) -> bool {
    let section = &object.obj.sections[section_index];
    let Some((owner_start, owner)) = section.splits.for_address(start) else { return false };
    let owner_end =
        if owner.end == 0 { (section.address + section.size) as u32 } else { owner.end };
    owner_start <= start && owner_end >= end && owner.unit == unit
}

#[allow(clippy::too_many_arguments)]
fn eligibility_reasons(
    size: u32,
    source_weak: bool,
    target_weak: bool,
    source_extent_known: bool,
    target_extent_known: bool,
    source_unit_explicit: bool,
    source_unit_wholly_owned: bool,
    template: bool,
    body_equal: bool,
    reloc_equal: bool,
    owner: Option<&str>,
    owner_autogenerated: bool,
    unit: &str,
) -> Vec<&'static str> {
    let mut reasons = Vec::new();
    if size < MIN_ANCHOR_BYTES {
        reasons.push("anchor is smaller than policy minimum");
    }
    if source_weak || target_weak {
        reasons.push("weak symbol cannot establish ownership");
    }
    if !source_extent_known || !target_extent_known {
        reasons.push("function extent is not completely known");
    }
    if !source_unit_explicit {
        reasons.push("source unit is autogenerated");
    }
    if !source_unit_wholly_owned {
        reasons.push("source function is not wholly owned by one unit");
    }
    if template {
        reasons.push("template instantiation cannot establish ownership alone");
    }
    if !body_equal {
        reasons.push("normalized bytes differ after hash lookup");
    }
    if !reloc_equal {
        reasons.push("relocation layout differs");
    }
    if owner.is_some_and(|name| name != unit && !owner_autogenerated) {
        reasons.push("target range is owned by another explicit unit");
    }
    reasons
}

fn hex(value: u32) -> String { format!("{value:#010X}") }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn eligibility_is_conservative_and_deterministic() {
        assert!(
            eligibility_reasons(
                128, false, false, true, true, true, true, false, true, true, None, false, "A",
            )
            .is_empty()
        );
        assert_eq!(
            eligibility_reasons(
                64,
                true,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                Some("B"),
                false,
                "A",
            ),
            vec![
                "anchor is smaller than policy minimum",
                "weak symbol cannot establish ownership",
                "function extent is not completely known",
                "source unit is autogenerated",
                "source function is not wholly owned by one unit",
                "template instantiation cannot establish ownership alone",
                "normalized bytes differ after hash lookup",
                "relocation layout differs",
                "target range is owned by another explicit unit",
            ]
        );
    }

    #[test]
    fn autogenerated_ownership_does_not_conflict() {
        assert!(
            eligibility_reasons(
                128,
                false,
                false,
                true,
                true,
                true,
                true,
                false,
                true,
                true,
                Some("auto_text"),
                true,
                "A",
            )
            .is_empty()
        );
    }

    #[test]
    fn duplicate_normalized_bodies_are_not_unique() {
        let hashes = HashMap::from([(7, vec![3]), (8, vec![4, 5])]);
        assert_eq!(unique_hash_node(&hashes, 7), Some(3));
        assert_eq!(unique_hash_node(&hashes, 8), None);
        assert_eq!(unique_hash_node(&hashes, 9), None);
    }

    #[test]
    fn body_confirmation_blocks_a_hash_collision() {
        let reasons = eligibility_reasons(
            128, false, false, true, true, true, true, false, false, true, None, false, "A",
        );
        assert_eq!(reasons, vec!["normalized bytes differ after hash lookup"]);
    }

    #[test]
    fn names_only_apply_the_template_exclusion() {
        assert!(!is_template_name("MisleadingButOrdinaryName"));
        assert!(is_template_name("rstl::vector<int>"));
        assert!(is_template_name("rstl::vector<int>::size() const"));
        assert!(!is_template_name("CBomb::CBomb(rstl::reserved_vector<CEntity*, 8>)"));
    }

    #[test]
    fn infers_one_base_class_insertion_without_a_magic_breakpoint() {
        let transform = infer_offset_transform(&[
            (0x40, 0x40),
            (0x60, 0x60),
            (0x158, 0x168),
            (0x17C, 0x18C),
            (0x190, 0x1A0),
        ])
        .unwrap();
        assert_eq!(transform.delta, 0x10);
        assert_eq!(transform.breakpoint, Some(0x158));
        assert_eq!(transform.changed_accesses, 3);
    }

    #[test]
    fn rejects_arbitrary_per_field_offset_changes() {
        assert!(infer_offset_transform(&[(0x158, 0x168), (0x170, 0x190)]).is_none());
        assert!(infer_offset_transform(&[(0x40, 0x50), (0x60, 0x60), (0x158, 0x168)]).is_none());
    }

    #[test]
    fn empty_evidence_serialization_is_deterministic() {
        let report = CoverageReport {
            schema: COVERAGE_SCHEMA,
            policy: CoveragePolicy {
                version: POLICY_VERSION,
                minimum_anchor_bytes: MIN_ANCHOR_BYTES,
                normalized_body_must_be_unique: true,
                confirm_normalized_bytes_after_hash: true,
                require_relocation_layout: true,
                require_known_extents: true,
                require_explicit_whole_source_ownership: true,
                reject_weak_symbols: true,
                reject_template_anchors: true,
                reject_conflicting_target_ownership: true,
                require_split_alignment: true,
                infer_this_relative_layout_shifts: true,
                minimum_layout_shift_functions: MIN_LAYOUT_SHIFT_FUNCTIONS,
                minimum_layout_shift_changed_accesses: MIN_LAYOUT_SHIFT_CHANGED_ACCESSES,
                minimum_layout_shift_bytes: MIN_LAYOUT_SHIFT_BYTES,
                maximum_layout_shift_segments: 2,
            },
            source: "source".into(),
            target: "target".into(),
            target_ownership_masked: true,
            source_units: Vec::new(),
            target_layout: Vec::new(),
        };
        let first = serde_json::to_string(&report).unwrap();
        assert_eq!(first, serde_json::to_string(&report).unwrap());
    }
}
