use std::collections::{BTreeMap, HashMap, HashSet};

use serde::Serialize;

use crate::{
    analysis::{
        callgraph::{FunctionNode, NodeIndex},
        fingerprint::normalized_body,
        matching::MatchTarget,
    },
    obj::ObjSectionKind,
    util::split::default_section_align,
};

pub const COVERAGE_SCHEMA: u32 = 1;
pub const POLICY_VERSION: u32 = 1;
pub const MIN_ANCHOR_BYTES: u32 = 128;

#[derive(Debug, Serialize)]
pub struct CoverageReport {
    pub schema: u32,
    pub policy: CoveragePolicy,
    pub source: String,
    pub target: String,
    pub target_ownership_masked: bool,
    pub source_units: Vec<CoverageUnit>,
    pub target_layout: Vec<TargetFunction>,
}

#[derive(Debug, Serialize)]
pub struct CoveragePolicy {
    pub version: u32,
    pub minimum_anchor_bytes: u32,
    pub normalized_body_must_be_unique: bool,
    pub confirm_normalized_bytes_after_hash: bool,
    pub require_relocation_layout: bool,
    pub require_known_extents: bool,
    pub require_explicit_whole_source_ownership: bool,
    pub reject_weak_symbols: bool,
    pub reject_template_anchors: bool,
    pub reject_conflicting_target_ownership: bool,
    pub require_split_alignment: bool,
}

#[derive(Debug, Serialize)]
pub struct CoverageUnit {
    pub name: String,
    pub code_bytes: u64,
    pub autogenerated: bool,
    pub source_functions: u32,
    pub no_exact_target_body: u32,
    pub name_only_candidates: u32,
    pub ambiguous_exact_bodies: u32,
    pub anchors: Vec<CoverageAnchor>,
}

#[derive(Debug, Serialize)]
pub struct CoverageAnchor {
    pub source_name: String,
    pub source_address: String,
    pub target_name: String,
    pub target_address: String,
    pub target_end: String,
    pub section: String,
    pub size: u32,
    pub source_local: bool,
    pub target_local: bool,
    pub source_weak: bool,
    pub target_weak: bool,
    pub source_extent_known: bool,
    pub target_extent_known: bool,
    pub source_unit_explicit: bool,
    pub source_unit_wholly_owned: bool,
    pub template_instantiation: bool,
    pub unique_source: bool,
    pub unique_target: bool,
    pub normalized_body_equal: bool,
    pub relocation_layout_equal: bool,
    pub required_alignment: u32,
    pub existing_target_owner: Option<String>,
    pub existing_owner_autogenerated: bool,
    pub eligible: bool,
    pub reasons: Vec<&'static str>,
}

#[derive(Debug, Serialize)]
pub struct TargetFunction {
    pub address: String,
    pub end: String,
    pub section: String,
    pub current_owner: Option<String>,
    pub owner_autogenerated: bool,
}

pub fn build_report(
    source: &MatchTarget,
    target: &MatchTarget,
    mask_target_ownership: bool,
) -> CoverageReport {
    let mut source_hashes: HashMap<u64, Vec<NodeIndex>> = HashMap::new();
    let mut target_hashes: HashMap<u64, Vec<NodeIndex>> = HashMap::new();
    for node in 0..source.graph.len() as NodeIndex {
        source_hashes.entry(source.fingerprints[node as usize].exact_hash).or_default().push(node);
    }
    for node in 0..target.graph.len() as NodeIndex {
        target_hashes.entry(target.fingerprints[node as usize].exact_hash).or_default().push(node);
    }
    let target_names: HashSet<&str> =
        (0..target.graph.len() as NodeIndex).map(|node| target.symbol_name(node)).collect();

    let mut units: BTreeMap<String, CoverageUnit> = BTreeMap::new();
    for (_, section, start, split) in source.obj.sections.all_splits() {
        let entry = units.entry(split.unit.clone()).or_insert_with(|| CoverageUnit {
            name: split.unit.clone(),
            code_bytes: 0,
            autogenerated: source.obj.is_unit_autogenerated(&split.unit),
            source_functions: 0,
            no_exact_target_body: 0,
            name_only_candidates: 0,
            ambiguous_exact_bodies: 0,
            anchors: Vec::new(),
        });
        if section.kind == ObjSectionKind::Code {
            let end =
                if split.end == 0 { (section.address + section.size) as u32 } else { split.end };
            entry.code_bytes += end.saturating_sub(start) as u64;
        }
    }

    for source_node in 0..source.graph.len() as NodeIndex {
        let Some(unit) = source.unit_of(source_node) else { continue };
        let source_name = source.symbol_name(source_node);
        if let Some(entry) = units.get_mut(unit) {
            entry.source_functions += 1;
        }
        let fingerprint = &source.fingerprints[source_node as usize];
        let source_candidate = unique_hash_node(&source_hashes, fingerprint.exact_hash);
        if source_candidate != Some(source_node) {
            if let Some(entry) = units.get_mut(unit) {
                entry.ambiguous_exact_bodies += 1;
            }
            continue;
        }
        if !target_hashes.contains_key(&fingerprint.exact_hash) {
            if let Some(entry) = units.get_mut(unit) {
                entry.no_exact_target_body += 1;
                entry.name_only_candidates += u32::from(target_names.contains(source_name));
            }
            continue;
        }
        let target_candidate = unique_hash_node(&target_hashes, fingerprint.exact_hash);
        if target_candidate.is_none() {
            if let Some(entry) = units.get_mut(unit) {
                entry.ambiguous_exact_bodies += 1;
            }
            continue;
        }
        let target_node = target_candidate.unwrap();
        let a = source.graph.node(source_node);
        let b = target.graph.node(target_node);
        let target_name = target.symbol_name(target_node);
        let target_owner = (!mask_target_ownership)
            .then(|| target.unit_of(target_node).map(str::to_string))
            .flatten();
        let owner_auto =
            target_owner.as_deref().is_some_and(|name| target.obj.is_unit_autogenerated(name));
        let source_body = normalized_body(&source.obj, a);
        let target_body = normalized_body(&target.obj, b);
        let source_extent_known =
            source.obj.symbols[a.symbol].size_known && source_body.len() == a.size as usize;
        let target_extent_known =
            target.obj.symbols[b.symbol].size_known && target_body.len() == b.size as usize;
        let body_equal = source_body == target_body;
        let reloc_equal = relocation_layout(a) == relocation_layout(b);
        let template = is_template_name(source_name) || is_template_name(target_name);
        let source_unit_explicit = !source.obj.is_unit_autogenerated(unit);
        let source_unit_wholly_owned =
            range_is_owned_by(source, a.section, a.address, a.address + a.size, unit);
        let section = &target.obj.sections[b.section];
        let align = required_alignment(target, b);
        let mut reasons = eligibility_reasons(
            a.size,
            source.is_weak(source_node),
            target.is_weak(target_node),
            source_extent_known,
            target_extent_known,
            source_unit_explicit,
            source_unit_wholly_owned,
            template,
            body_equal,
            reloc_equal,
            target_owner.as_deref(),
            owner_auto,
            unit,
        );
        if b.address % align != 0 || (b.address + b.size) % align != 0 {
            reasons.push("function range is not split-aligned");
        }
        units
            .entry(unit.to_string())
            .or_insert_with(|| CoverageUnit {
                name: unit.to_string(),
                code_bytes: 0,
                autogenerated: source.obj.is_unit_autogenerated(unit),
                source_functions: 0,
                no_exact_target_body: 0,
                name_only_candidates: 0,
                ambiguous_exact_bodies: 0,
                anchors: Vec::new(),
            })
            .anchors
            .push(CoverageAnchor {
                source_name: source_name.to_string(),
                source_address: hex(a.address),
                target_name: if mask_target_ownership {
                    String::new()
                } else {
                    target_name.to_string()
                },
                target_address: hex(b.address),
                target_end: hex(b.address + b.size),
                section: section.name.clone(),
                size: a.size,
                source_local: source.is_local(source_node),
                target_local: target.is_local(target_node),
                source_weak: source.is_weak(source_node),
                target_weak: target.is_weak(target_node),
                source_extent_known,
                target_extent_known,
                source_unit_explicit,
                source_unit_wholly_owned,
                template_instantiation: template,
                unique_source: true,
                unique_target: true,
                normalized_body_equal: body_equal,
                relocation_layout_equal: reloc_equal,
                required_alignment: align,
                existing_target_owner: target_owner,
                existing_owner_autogenerated: owner_auto,
                eligible: reasons.is_empty(),
                reasons,
            });
    }

    for unit in units.values_mut() {
        unit.anchors
            .sort_by(|a, b| b.size.cmp(&a.size).then(a.target_address.cmp(&b.target_address)));
    }
    let target_layout = target
        .layout()
        .iter()
        .map(|&index| {
            let node = target.graph.node(index);
            let owner = (!mask_target_ownership)
                .then(|| target.unit_of(index).map(str::to_string))
                .flatten();
            TargetFunction {
                address: hex(node.address),
                end: hex(node.address + node.size),
                section: target.obj.sections[node.section].name.clone(),
                owner_autogenerated: owner
                    .as_deref()
                    .is_some_and(|name| target.obj.is_unit_autogenerated(name)),
                current_owner: owner,
            }
        })
        .collect();

    CoverageReport {
        schema: COVERAGE_SCHEMA,
        policy: CoveragePolicy {
            version: POLICY_VERSION,
            minimum_anchor_bytes: MIN_ANCHOR_BYTES,
            normalized_body_must_be_unique: true,
            confirm_normalized_bytes_after_hash: true,
            require_relocation_layout: true,
            require_known_extents: true,
            require_explicit_whole_source_ownership: true,
            reject_weak_symbols: true,
            reject_template_anchors: true,
            reject_conflicting_target_ownership: true,
            require_split_alignment: true,
        },
        source: source.name.clone(),
        target: target.name.clone(),
        target_ownership_masked: mask_target_ownership,
        source_units: units.into_values().collect(),
        target_layout,
    }
}

fn required_alignment(target: &MatchTarget, node: &FunctionNode) -> u32 {
    let section = &target.obj.sections[node.section];
    target
        .obj
        .symbols
        .for_section_range(node.section, node.address..node.address + node.size)
        .filter(|&(_, symbol)| symbol.size_known && symbol.size > 0)
        .filter_map(|(_, symbol)| symbol.align)
        .max()
        .unwrap_or(default_section_align(section) as u32)
        .max(default_section_align(section) as u32)
}

fn relocation_layout(node: &FunctionNode) -> Vec<(u32, crate::obj::ObjRelocKind)> {
    node.refs.iter().map(|reference| (reference.offset, reference.kind)).collect()
}

fn is_template_name(name: &str) -> bool { name.contains('<') || name.contains('>') }

fn unique_hash_node(hashes: &HashMap<u64, Vec<NodeIndex>>, hash: u64) -> Option<NodeIndex> {
    let nodes = hashes.get(&hash)?;
    (nodes.len() == 1).then_some(nodes[0])
}

/// Confirm that the complete function interval belongs to one explicit source
/// split, rather than inferring ownership from its first instruction alone.
fn range_is_owned_by(
    object: &MatchTarget,
    section_index: crate::obj::SectionIndex,
    start: u32,
    end: u32,
    unit: &str,
) -> bool {
    let section = &object.obj.sections[section_index];
    let Some((owner_start, owner)) = section.splits.for_address(start) else { return false };
    let owner_end =
        if owner.end == 0 { (section.address + section.size) as u32 } else { owner.end };
    owner_start <= start && owner_end >= end && owner.unit == unit
}

#[allow(clippy::too_many_arguments)]
fn eligibility_reasons(
    size: u32,
    source_weak: bool,
    target_weak: bool,
    source_extent_known: bool,
    target_extent_known: bool,
    source_unit_explicit: bool,
    source_unit_wholly_owned: bool,
    template: bool,
    body_equal: bool,
    reloc_equal: bool,
    owner: Option<&str>,
    owner_autogenerated: bool,
    unit: &str,
) -> Vec<&'static str> {
    let mut reasons = Vec::new();
    if size < MIN_ANCHOR_BYTES {
        reasons.push("anchor is smaller than policy minimum");
    }
    if source_weak || target_weak {
        reasons.push("weak symbol cannot establish ownership");
    }
    if !source_extent_known || !target_extent_known {
        reasons.push("function extent is not completely known");
    }
    if !source_unit_explicit {
        reasons.push("source unit is autogenerated");
    }
    if !source_unit_wholly_owned {
        reasons.push("source function is not wholly owned by one unit");
    }
    if template {
        reasons.push("template instantiation cannot establish ownership alone");
    }
    if !body_equal {
        reasons.push("normalized bytes differ after hash lookup");
    }
    if !reloc_equal {
        reasons.push("relocation layout differs");
    }
    if owner.is_some_and(|name| name != unit && !owner_autogenerated) {
        reasons.push("target range is owned by another explicit unit");
    }
    reasons
}

fn hex(value: u32) -> String { format!("{value:#010X}") }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn eligibility_is_conservative_and_deterministic() {
        assert!(
            eligibility_reasons(
                128, false, false, true, true, true, true, false, true, true, None, false, "A",
            )
            .is_empty()
        );
        assert_eq!(
            eligibility_reasons(
                64,
                true,
                false,
                false,
                true,
                false,
                false,
                true,
                false,
                false,
                Some("B"),
                false,
                "A",
            ),
            vec![
                "anchor is smaller than policy minimum",
                "weak symbol cannot establish ownership",
                "function extent is not completely known",
                "source unit is autogenerated",
                "source function is not wholly owned by one unit",
                "template instantiation cannot establish ownership alone",
                "normalized bytes differ after hash lookup",
                "relocation layout differs",
                "target range is owned by another explicit unit",
            ]
        );
    }

    #[test]
    fn autogenerated_ownership_does_not_conflict() {
        assert!(
            eligibility_reasons(
                128,
                false,
                false,
                true,
                true,
                true,
                true,
                false,
                true,
                true,
                Some("auto_text"),
                true,
                "A",
            )
            .is_empty()
        );
    }

    #[test]
    fn duplicate_normalized_bodies_are_not_unique() {
        let hashes = HashMap::from([(7, vec![3]), (8, vec![4, 5])]);
        assert_eq!(unique_hash_node(&hashes, 7), Some(3));
        assert_eq!(unique_hash_node(&hashes, 8), None);
        assert_eq!(unique_hash_node(&hashes, 9), None);
    }

    #[test]
    fn body_confirmation_blocks_a_hash_collision() {
        let reasons = eligibility_reasons(
            128, false, false, true, true, true, true, false, false, true, None, false, "A",
        );
        assert_eq!(reasons, vec!["normalized bytes differ after hash lookup"]);
    }

    #[test]
    fn names_only_apply_the_template_exclusion() {
        assert!(!is_template_name("MisleadingButOrdinaryName"));
        assert!(is_template_name("rstl::vector<int>"));
    }

    #[test]
    fn empty_evidence_serialization_is_deterministic() {
        let report = CoverageReport {
            schema: COVERAGE_SCHEMA,
            policy: CoveragePolicy {
                version: POLICY_VERSION,
                minimum_anchor_bytes: MIN_ANCHOR_BYTES,
                normalized_body_must_be_unique: true,
                confirm_normalized_bytes_after_hash: true,
                require_relocation_layout: true,
                require_known_extents: true,
                require_explicit_whole_source_ownership: true,
                reject_weak_symbols: true,
                reject_template_anchors: true,
                reject_conflicting_target_ownership: true,
                require_split_alignment: true,
            },
            source: "source".into(),
            target: "target".into(),
            target_ownership_masked: true,
            source_units: Vec::new(),
            target_layout: Vec::new(),
        };
        let first = serde_json::to_string(&report).unwrap();
        assert_eq!(first, serde_json::to_string(&report).unwrap());
    }
}
